# Minimal Jekyll configuration for GitHub Pages

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

# Plugins required by the theme
plugins:
  - jekyll-include-cache

# Site settings
title: "WCCA 2025 Workshop"
logo: "/assets/images/logo-placeholder.svg"
masthead_title: ""

# Optional build settings
markdown: kramdown